### PR TITLE
Add option to include external JAVA_HOME setting for gradle task

### PR DESCRIPTION
**Pull request by robbavey**

### CODE REVIEW

**Comment by robbavey** [comment]
Note that this requires https://github.com/elastic/infra/pull/34352 to be committed first

**Comment by robbavey** [comment]
cc @gtback

**Comment by gtback** [comment]
Thanks for the ping, @robbavey . I'm fine with these changes; let me know if you need my help with anything.

**Review by karenzone — APPROVED** [review]
Thanks for making these changes, Rob. LGTM

**Comment by robbavey** [comment]
Note for completeness: This commit fixes https://github.com/elastic/docs-tools/issues/64

**Pull request merged**
